"""Real rename tables 3rd time

Revision ID: 33f2043ff3db
Revises: 4c7bb018bbd8
Create Date: 2024-05-28 23:07:36.917847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f2043ff3db'
down_revision = '4c7bb018bbd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
