"""Real rename tables 2nd time

Revision ID: 4c7bb018bbd8
Revises: d4c5889aa666
Create Date: 2024-05-28 23:07:20.222359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7bb018bbd8'
down_revision = 'd4c5889aa666'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('physical_number', sa.Integer(), nullable=True),
    sa.Column('ready_to_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_number')
    )
    op.create_index(op.f('ix_pcs_id'), 'pcs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tg_tag', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tg_tag'), 'users', ['tg_tag'], unique=True)
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_id', table_name='Users')
    op.drop_index('ix_Users_tg_tag', table_name='Users')
    op.drop_table('Users')
    op.drop_index('ix_PCs_id', table_name='PCs')
    op.drop_table('PCs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PCs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PCs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('physical_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ready_to_use', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PCs_pkey'),
    sa.UniqueConstraint('physical_number', name='PCs_physical_number_key')
    )
    op.create_index('ix_PCs_id', 'PCs', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tg_tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey')
    )
    op.create_index('ix_Users_tg_tag', 'Users', ['tg_tag'], unique=False)
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_tg_tag'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pcs_id'), table_name='pcs')
    op.drop_table('pcs')
    # ### end Alembic commands ###
