"""Add session setting and timeperiod

Revision ID: 63f329086bc4
Revises: b52f91c954cc
Create Date: 2024-05-26 18:32:50.801962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f329086bc4'
down_revision = 'b52f91c954cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_setting_id', table_name='setting')
    op.drop_table('setting')
    op.add_column('user', sa.Column('tg_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_tg_tag'), 'user', ['tg_tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_tag'), table_name='user')
    op.drop_column('user', 'tg_tag')
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='setting_pkey'),
    sa.UniqueConstraint('slug', name='setting_slug_key')
    )
    op.create_index('ix_setting_id', 'setting', ['id'], unique=False)
    # ### end Alembic commands ###
