"""Delete blog functionality

Revision ID: 780eefad5136
Revises: a2e6540ab5ec
Create Date: 2024-05-25 13:08:57.913795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780eefad5136'
down_revision = 'a2e6540ab5ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
