"""Change slug to string

Revision ID: a736a13d25bd
Revises: 63f329086bc4
Create Date: 2024-05-26 18:36:51.844836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a736a13d25bd'
down_revision = '63f329086bc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
