"""Add PC model

Revision ID: b52f91c954cc
Revises: 780eefad5136
Create Date: 2024-05-25 13:34:27.661509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52f91c954cc'
down_revision = '780eefad5136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
