"""Real rename tables

Revision ID: d4c5889aa666
Revises: f65a16859c49
Create Date: 2024-05-28 23:04:01.059167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c5889aa666'
down_revision = 'f65a16859c49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
