"""rename tables

Revision ID: f65a16859c49
Revises: a736a13d25bd
Create Date: 2024-05-28 23:03:02.582778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65a16859c49'
down_revision = 'a736a13d25bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PCs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('physical_number', sa.Integer(), nullable=True),
    sa.Column('ready_to_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_number')
    )
    op.create_index(op.f('ix_PCs_id'), 'PCs', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tg_tag', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_tg_tag'), 'Users', ['tg_tag'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_tg_tag', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_setting_id', table_name='setting')
    op.drop_table('setting')
    op.drop_index('ix_pc_id', table_name='pc')
    op.drop_table('pc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('physical_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ready_to_use', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pc_pkey'),
    sa.UniqueConstraint('physical_number', name='pc_physical_number_key')
    )
    op.create_index('ix_pc_id', 'pc', ['id'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='setting_pkey'),
    sa.UniqueConstraint('slug', name='setting_slug_key')
    )
    op.create_index('ix_setting_id', 'setting', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tg_tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_tg_tag', 'user', ['tg_tag'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_Users_tg_tag'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_PCs_id'), table_name='PCs')
    op.drop_table('PCs')
    # ### end Alembic commands ###
